apiVersion: v1
kind: ConfigMap
metadata:
  name: work-order-service-config
  namespace: globalfieldops
  labels:
    app: work-order-service
    app.kubernetes.io/part-of: globalfieldops
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-workorder:5432/workorder_db"
  SPRING_DATASOURCE_USERNAME: "workorder"
  TECHNICIAN_SERVICE_URL: "http://technician-service.globalfieldops.svc.cluster.local:8081"
  AUDIT_SERVICE_URL: "http://audit-service.globalfieldops.svc.cluster.local:8083"
