apiVersion: v1
kind: Secret
metadata:
  name: work-order-service-secret
  namespace: globalfieldops
  labels:
    app: work-order-service
    app.kubernetes.io/part-of: globalfieldops
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "workorder_secret"
