apiVersion: v1
kind: Service
metadata:
  name: work-order-service
  namespace: globalfieldops
  labels:
    app: work-order-service
    app.kubernetes.io/part-of: globalfieldops
spec:
  type: ClusterIP
  selector:
    app: work-order-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
