apiVersion: v1
kind: Secret
metadata:
  name: audit-service-secret
  namespace: globalfieldops
  labels:
    app: audit-service
    app.kubernetes.io/part-of: globalfieldops
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "audit_secret"
