apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: globalfieldops
  labels:
    app: audit-service
    app.kubernetes.io/part-of: globalfieldops
spec:
  type: ClusterIP
  selector:
    app: audit-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
