apiVersion: v1
kind: Secret
metadata:
  name: technician-service-secret
  namespace: globalfieldops
  labels:
    app: technician-service
    app.kubernetes.io/part-of: globalfieldops
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "technician_secret"
