apiVersion: v1
kind: Service
metadata:
  name: technician-service
  namespace: globalfieldops
  labels:
    app: technician-service
    app.kubernetes.io/part-of: globalfieldops
spec:
  type: ClusterIP
  selector:
    app: technician-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
